#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

name='Best School'

i=0

while [ $i -le 9 ]
  do
    if [[ $i -eq 10 ]]
      then
        echo $name
        echo 'Hi'
      else
        echo $name
    fi
    ((i++))
  done
