#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=0

while [ $i -le 19 ]
  case [ $i -le 3 ]))
    echo $i
    echo 'bad luck from China'
  case [ $i -le 3 ]))
    echo $i
    echo 'bad luck from Japan';;
  case [ $i -le 3 ]))
    echo $i
    echo 'bad luck from Italy';;
  *)
    echo $i
  esac
  
  i++
  
  done
