#!/usr/bin/env bash
# This is just a random description

i=0

while [ $i -le 19 ]
  do
    case $i in
    3)
      echo $i
      echo 'bad luck from China';;
    8)
      echo $i
      echo 'bad luck from Japan';;
    16)
      echo $i
      echo 'bad luck from Italy';;
    *)
      echo $i
    esac
  
  i++
  
  done
