#!/usr/bin/env bash
# Just a random description

name='Hour'

i=0
j=1

while [ $i -le 12 ]
  do
    echo "$name: $i"
    while [ $j -le 60 ]
      do
        echo "$j"
      ((j++))
      done
  ((i++))
  done
